sudo: required
  
services:
  - docker

language: scala

scala:
  - 2.11.8

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker run -d --net=host --name mongo mongo:3.2
script:
  - ./sbt clean compile docker:publishLocal
  - docker run -d -p 9000:9000 --net=host sdkman/sdkman-candidates:1.0.0-SNAPSHOT
  - ./sbt test

after_success:
  - sbt docker:publish

cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"

# blacklist
branches:
  except:
    - RELEASE
